CREATE DATABASE kundenverwaltung;
USE KUNDENVERWALTUNG;

CREATE TABLE IF NOT EXISTS kunde(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phonenumber VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE
);
